/**
 * docxBuilders.ts
 * Generates real .docx files using the `docx` library.
 * Each builder returns a Promise<Blob> with the correct MIME type.
 *
 * These replace the RTF builders which were renamed .docx but were
 * actually RTF format — causing "unreadable content" warnings in Word.
 */
import {
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  TextRun,
  AlignmentType,
  BorderStyle,
} from 'docx'

import type { NdaWizardData } from '../pages/user-dashboard/NdaWizardModal'
import type { EmploymentWizardData } from '../pages/user-dashboard/EmploymentWizardModal'
import type { PrivacyPolicyWizardData } from '../pages/user-dashboard/PrivacyPolicyWizardModal'
import type { FounderAgreementWizardData } from '../pages/user-dashboard/FounderAgreementWizardModal'
import type { ServiceAgreementWizardData } from '../pages/user-dashboard/ServiceAgreementWizardModal'
import type { SlaWizardData } from '../pages/user-dashboard/SlaWizardModal'

// ── Shared helpers ────────────────────────────────────────────────────────────

const fmtDate = (d: string | null) =>
  d ? new Date(d).toLocaleDateString('en-ZA') : new Date().toLocaleDateString('en-ZA')

const val = (v: string | undefined | null) => v || '—'
const yn  = (v: boolean) => (v ? 'Yes' : 'No')

/** Bold heading paragraph */
const h1 = (text: string) =>
  new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun({ text, bold: true, size: 28 })] })

const h2 = (text: string) =>
  new Paragraph({ heading: HeadingLevel.HEADING_2, children: [new TextRun({ text, bold: true, size: 24 })] })

/** Label: value row */
const row = (label: string, value: string) =>
  new Paragraph({
    children: [
      new TextRun({ text: `${label}: `, bold: true }),
      new TextRun({ text: val(value) }),
    ],
    indent: { left: 360 },
  })

/** Thin horizontal separator */
const sep = () =>
  new Paragraph({
    border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: 'AAAAAA' } },
    spacing: { before: 120, after: 120 },
    children: [],
  })

/** Italic disclaimer footer */
const disclaimer = () =>
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { before: 400 },
    children: [
      new TextRun({
        text: 'DISCLAIMER: This document is generated for reference purposes only. It does not constitute legal advice. Consult a qualified attorney.',
        italics: true,
        size: 18,
        color: '888888',
      }),
    ],
  })

const pack = (sections: Paragraph[]) =>
  Packer.toBlob(
    new Document({
      sections: [{ properties: {}, children: sections }],
      creator: 'The Startup Legal',
    }),
  )

// ── NDA ───────────────────────────────────────────────────────────────────────

export async function buildNdaDocx(data: NdaWizardData, completedAt: string | null): Promise<Blob> {
  const fmtAddr = (a: NdaWizardData['party_a']['address']) =>
    [a.street_number, a.building, a.street_name, a.suburb, a.city, a.province, a.postal_code, a.country].filter(Boolean).join(', ')

  return pack([
    h1('NON-DISCLOSURE AGREEMENT'),
    row('Date', fmtDate(completedAt)),
    row('Generated by', 'The Startup Legal'),
    sep(),
    h2('1. Parties'),
    row('Agreement Type', data.agreement_type),
    sep(),
    h2('Party A'),
    row('Type', data.party_a.entity_type),
    row('Legal Name', data.party_a.legal_name || data.party_a.full_names),
    row('Registration No.', data.party_a.reg_number),
    row('Address', fmtAddr(data.party_a.address)),
    row('Email', data.party_a.email),
    row('Signatory', `${data.party_a.signatory_name} (${data.party_a.signatory_capacity})`),
    sep(),
    h2('Party B'),
    row('Type', data.party_b.entity_type),
    row('Legal Name', data.party_b.legal_name || data.party_b.full_names),
    row('Registration No.', data.party_b.reg_number),
    row('Address', fmtAddr(data.party_b.address)),
    row('Email', data.party_b.email),
    row('Signatory', `${data.party_b.signatory_name} (${data.party_b.signatory_capacity})`),
    sep(),
    h2('2. Purpose & Scope'),
    row('Purpose', data.purpose),
    row('CI Definition', data.ci_definition),
    row('Must be marked confidential', yn(data.marking_required)),
    sep(),
    h2('3. Obligations'),
    row('Duration', `${data.duration_years} years, from ${data.duration_start}`),
    row('Return / Destroy', data.return_or_destroy),
    row('Archival copy', yn(data.archival_copy)),
    row('Non-solicitation', data.non_solicit ? `Yes (${data.non_solicit_months} months)` : 'No'),
    sep(),
    h2('4. Legal + Signing'),
    row('Governing Law', data.governing_law),
    row('Dispute Forum', data.dispute_forum),
    row('Signature Method', data.signature_method),
    row('Signing Order', data.signing_order),
    sep(),
    disclaimer(),
  ])
}

// ── Employment Offer Letter ───────────────────────────────────────────────────

export async function buildEmploymentDocx(d: EmploymentWizardData, completedAt: string | null): Promise<Blob> {
  const salary = d.salaryAmount ? `R${Number(d.salaryAmount).toLocaleString('en-ZA')} ${d.salaryFrequency}` : '—'
  return pack([
    h1('EMPLOYMENT OFFER LETTER'),
    row('Date', fmtDate(completedAt)),
    row('Generated by', 'The Startup Legal'),
    sep(),
    h2('1. Employer Details'),
    row('Company Name', d.companyName),
    row('Registration No.', d.companyReg),
    row('Address', d.employerAddress),
    row('Contact Person', d.employerContactPerson),
    row('Email', d.employerEmail),
    sep(),
    h2('2. Employee Details'),
    row('Full Name', d.employeeFullName),
    row('ID / Passport', d.employeeIdNumber),
    row('Address', d.employeeAddress),
    row('Email', d.employeeEmail),
    row('Phone', d.employeePhone),
    sep(),
    h2('3. Employment Information'),
    row('Job Title', d.jobTitle),
    row('Department', d.department),
    row('Employment Type', d.employmentType),
    row('Start Date', d.startDate),
    row('Probation Period', d.probationPeriod),
    row('Working Hours', d.workingHours),
    row('Work Location', d.workLocation),
    sep(),
    h2('4. Salary & Benefits'),
    row('Salary', salary),
    row('Bonuses', d.bonuses),
    row('Leave Entitlement', d.leaveEntitlement),
    row('Medical Benefits', d.medicalBenefits),
    row('Pension', d.pension),
    row('Other Benefits', d.otherBenefits),
    sep(),
    h2('5. Contract Terms'),
    row('Notice Period', d.noticePeriod),
    row('Governing Law', d.governingLaw),
    row('Confidentiality Clause', yn(d.confidentialityClause)),
    row('Intellectual Property Clause', yn(d.intellectualPropertyClause)),
    row('Non-Compete Clause', yn(d.nonCompeteClause)),
    sep(),
    disclaimer(),
  ])
}

// ── Privacy Policy ────────────────────────────────────────────────────────────

export async function buildPrivacyPolicyDocx(d: PrivacyPolicyWizardData, completedAt: string | null): Promise<Blob> {
  const purposeRows = d.purposes.flatMap((purpose, index) => [
    h2(`Purpose ${index + 1}`),
    row('Purpose', purpose.purpose),
    row('Categories', purpose.categories),
    row('Lawful Basis', purpose.basis),
    row('LI Statement', purpose.liStatement),
  ])

  const retentionRows = d.retention.flatMap((retention, index) => [
    h2(`Retention ${index + 1}`),
    row('Category', retention.category),
    row('Period', retention.period),
    row('Reason', retention.reason),
  ])

  const thirdPartyRows = d.thirdParties.flatMap((party, index) => [
    h2(`Third Party ${index + 1}`),
    row('Name', party.name),
    row('Purpose', party.purpose),
    row('Country', party.country),
  ])

  const cookieRows = d.cookies.flatMap((cookie, index) => [
    h2(`Cookie ${index + 1}`),
    row('Name', cookie.name),
    row('Purpose', cookie.purpose),
    row('Duration', cookie.duration),
    row('Necessary', cookie.necessary),
  ])

  return pack([
    h1('PRIVACY & COOKIES POLICY'),
    row('Date', fmtDate(completedAt)),
    row('Generated by', 'The Startup Legal'),
    sep(),
    h2('1. Who you are'),
    row('Responsible Party', d.responsibleParty),
    row('Confirmed', yn(d.responsiblePartyConfirmed)),
    row('Information Officer', d.officerFullNames),
    row('ID Number', d.officerIdNumber),
    row('Officer Email', d.officerEmail),
    row('Privacy Email', d.privacyEmail),
    row('Domains', d.domains.filter(Boolean).join(', ')),
    sep(),
    h2('2. What you collect'),
    row('PI Categories', d.piCategories.join(', ')),
    row('Special PI', d.specialPi.join(', ') || 'None'),
    row('Special PI Basis', d.specialPiBasis),
    row('Children Data', yn(d.childrenData)),
    row('Children Consent', d.childrenConsent),
    sep(),
    h2('3. Why & basis'),
    ...purposeRows,
    ...retentionRows,
    sep(),
    h2('4. Who else sees it'),
    ...thirdPartyRows,
    row('Cross-border Transfers', yn(d.crossBorder)),
    row('Transfer Countries', d.crossBorderCountries.join(', ')),
    row('Transfer Basis', d.transferBasis),
    row('Direct Marketing', yn(d.directMarketing)),
    sep(),
    h2('5. Cookies'),
    ...cookieRows,
    row('Cookie Consent', d.cookieConsent),
    row('Analytics Provider', d.analyticsProvider),
    sep(),
    h2('6. Publication'),
    row('DSR Channel', d.dsrChannel),
    row('DSR Days', d.dsrDays),
    row('Security Summary', d.securitySummary.join(', ')),
    row('Effective Date', d.effectiveDate),
    row('Automated Decisions', yn(d.automatedDecisions)),
    sep(),
    disclaimer(),
  ])
}

// ── Founder Agreement ─────────────────────────────────────────────────────────

export async function buildFounderAgreementDocx(d: FounderAgreementWizardData, completedAt: string | null): Promise<Blob> {
  const founderRows = d.founders.flatMap((f, i) => [
    h2(`Founder ${i + 1}`),
    row('Full names', f.fullNames),
    row('Identity number', f.idNumber),
    row('Role', f.role),
    row('Time commitment', f.commitment),
    row('Equity', f.equityPct ? `${f.equityPct}%` : '—'),
    row('Capital contributed', f.capital),
  ])
  const priorIpRows = d.priorIpNil
    ? [row('Pre-existing IP', 'Nothing to declare')]
    : d.priorIp.flatMap((p, i) => [
        h2(`Prior IP ${i + 1}`),
        row('Founder', p.founder),
        row('Description', p.description),
        row('Date created', p.dateCreated),
        row('Treatment', p.treatment),
      ])
  const digitalRows = d.digitalAssets.flatMap((a, i) => [
    h2(`Digital asset ${i + 1}`),
    row('Asset', a.asset),
    row('Current holder', a.currentHolder),
    row('Transfer date', a.transferDate),
  ])
  const sigRows = d.signatories.map((s, i) => row(`Signatory ${i + 1}`, `${val(s.name)} (${val(s.capacity)})`))
  return pack([
    h1("FOUNDERS' AGREEMENT & IP ASSIGNMENT"),
    row('Date', fmtDate(completedAt)),
    row('Generated by', 'The Startup Legal'),
    sep(),
    h2('1. Company Status'),
    row('Incorporated', d.isIncorporated),
    ...(d.isIncorporated === 'Yes'
      ? [row('Company Name', d.companyName)]
      : [row('Intended name', d.intendedName), row('Target incorporation', d.targetIncorporation)]),
    sep(),
    h2('2. Founders & Equity'),
    ...founderRows,
    sep(),
    h2('3. Vesting'),
    row('Vesting applies', d.vestingApplies),
    ...(d.vestingApplies === 'Yes' ? [
      row('Vesting period (months)', d.vestingMonths),
      row('Cliff (months)', d.cliffMonths),
      row('Frequency', d.vestingFrequency),
      row('Acceleration', d.acceleration),
      row('Good leaver', d.goodLeaver.join('; ')),
      row('Bad leaver consequence', d.badLeaverEffect),
    ] : []),
    sep(),
    h2('4. Decisions & Roles'),
    row('Decision model', d.decisionModel),
    row('Reserved matters', d.reservedMatters.join('; ')),
    ...(d.reservedMatters.includes('Take on debt above a threshold') ? [row('Debt threshold', d.debtThreshold)] : []),
    row('Removal process', d.removalProcess),
    row('Departure role', d.departureRole),
    sep(),
    h2('5. Intellectual Property'),
    row('IP assignment', 'Yes — assignment applies'),
    row('Assignment covers pre-incorporation work', d.ipPreIncorporation),
    ...priorIpRows,
    row('Publicly funded', d.publiclyFunded),
    row('Created while employed elsewhere', d.createdAtEmployer),
    ...digitalRows,
    sep(),
    h2('6. Protections & Legal'),
    row('Confidentiality', d.confidentiality),
    row('Non-solicitation', d.nonSolicit),
    row('Restraint of trade', d.restraint),
    ...(d.restraint === 'Yes' ? [row('Restraint duration (months)', d.restraintMonths), row('Restraint area', d.restraintArea)] : []),
    row('Deadlock mechanism', d.deadlock),
    row('Dispute resolution', d.disputeForum),
    row('Governing law', d.governingLaw),
    ...sigRows,
    sep(),
    disclaimer(),
  ])
}

// ── Service Agreement ─────────────────────────────────────────────────────────

export async function buildServiceAgreementDocx(d: ServiceAgreementWizardData, completedAt: string | null): Promise<Blob> {
  return pack([
    h1('SERVICE AGREEMENT'),
    row('Date', fmtDate(completedAt)),
    row('Generated by', 'The Startup Legal'),
    sep(),
    h2('1. Parties'),
    h2('Service Provider'),
    row('Legal Name', d.providerName),
    row('Registration No.', d.providerReg),
    row('Address', d.providerAddress),
    h2('Client'),
    row('Legal Name', d.clientName),
    row('Registration No.', d.clientReg),
    row('Address', d.clientAddress),
    row('Contact Name', d.contactName),
    row('Contact Email', d.contactEmail),
    row('Contact Phone', d.contactPhone),
    sep(),
    h2('2. Services'),
    row('Services Description', d.servicesDescription),
    row('Scope of Work', d.scopeOfWork),
    row('Deliverables', d.deliverables),
    sep(),
    h2('3. Fees & Pricing'),
    row('Pricing', d.pricing),
    row('Payment Terms', d.paymentTerms),
    row('Billing Frequency', d.billingFrequency),
    sep(),
    h2('4. Service Levels'),
    row('Availability', d.availability),
    row('Response Time', d.responseTime),
    row('Resolution Time', d.resolutionTime),
    row('Support Hours', d.supportHours),
    sep(),
    h2('5. Responsibilities'),
    row('Provider Responsibilities', d.providerResponsibilities),
    row('Client Responsibilities', d.clientResponsibilities),
    sep(),
    h2('6. Term & Termination'),
    row('Start Date', d.startDate),
    row('End Date', d.endDate),
    row('Renewal', d.renewal),
    row('Termination Notice', d.terminationNotice),
    sep(),
    h2('7. Legal'),
    row('Confidentiality', d.confidentiality),
    row('Liability', d.liability),
    row('Governing Law', d.governingLaw),
    row('Jurisdiction', d.jurisdiction),
    sep(),
    disclaimer(),
  ])
}

// ── Service Level Agreement (SLA) ─────────────────────────────────────────────

export async function buildSlaDocx(d: SlaWizardData, completedAt: string | null): Promise<Blob> {
  const v = (s: string | undefined | null) => s || '—'
  const yn = (b: boolean) => (b ? 'Yes' : 'No')

  return pack([
    h1('SERVICE LEVEL AGREEMENT (SLA)'),
    row('Date', fmtDate(completedAt)),
    row('Generated by', 'The Startup Legal'),
    sep(),
    h2('1. Parties'),
    h2('Service Provider'),
    row('Name', d.provider?.legalName || d.provider?.fullNames || d.providerName),
    row('Reg No.', d.provider?.regNumber || d.providerReg),
    row('Email', d.provider?.email || d.providerEmail),
    h2('Customer'),
    row('Name', d.customer?.legalName || d.customer?.fullNames || d.customerName),
    row('Reg No.', d.customer?.regNumber || d.customerReg),
    row('Email', d.customer?.email || d.customerEmail),
    sep(),
    h2('2. Agreement Details'),
    row('Service Description', d.serviceDescription),
    row('Start Date', d.startDate),
    row('Term', d.termType),
    ...(d.termType === 'Fixed end date' ? [row('End Date', d.endDate)] : []),
    sep(),
    h2('3. Modules'),
    row('Selected', d.modules.length > 0 ? d.modules.join(', ') : '—'),
    ...(d.modules.includes('Availability') ? [
      sep(),
      h2('4. Availability'),
      row('Uptime Target', d.uptimeTarget ? `${d.uptimeTarget}%` : '—'),
      row('Measurement Period', d.uptimePeriod),
      row('Exclusions', d.uptimeExclusions.join(', ') || '—'),
    ] : []),
    ...(d.modules.includes('Support') ? [
      sep(),
      h2('5. Support'),
      row('Support Hours', d.supportHours),
      ...(d.supportHours === 'Custom' ? [row('Custom Hours', d.supportHoursCustom)] : []),
      row('Support Channels', d.supportChannels.join(', ') || '—'),
    ] : []),
    ...(d.modules.includes('Incident response') ? [
      sep(),
      h2('6. Incident Response'),
      row('Severity Model', yn(d.useSeverityModel)),
      ...d.severityTargets.map((t) => row(t.severity, `Response: ${v(t.responseTarget)} | Resolution: ${v(t.resolutionTarget)}`)),
      row('Escalation Contacts', d.escalationContacts.map((c) => `${c.name} (${c.role}) ${c.email}`).join('; ') || '—'),
    ] : []),
    ...(d.modules.includes('Maintenance') ? [
      sep(),
      h2('7. Maintenance'),
      row('Planned Window', d.maintenanceWindow),
      row('Notice Period', d.maintenanceNoticeHours ? `${d.maintenanceNoticeHours} hours` : '—'),
      row('Emergency Permitted', yn(d.emergencyMaintenance)),
    ] : []),
    ...(d.modules.includes('Backups and restore') ? [
      sep(),
      h2('8. Backups and Restore'),
      row('Backup Frequency', d.backupFrequency),
      row('RTO', d.rtoHours ? `${d.rtoHours} hours` : '—'),
      row('RPO', d.rpoHours ? `${d.rpoHours} hours` : '—'),
      row('Retention', d.backupRetentionDays ? `${d.backupRetentionDays} days` : '—'),
    ] : []),
    ...(d.modules.includes('Security') ? [
      sep(),
      h2('9. Security'),
      row('Commitments', d.securityCommitments.join(', ') || '—'),
      row('Breach Notification', d.breachNoticeHours ? `${d.breachNoticeHours} hours` : '—'),
    ] : []),
    ...(d.modules.includes('Service credits') ? [
      sep(),
      h2('10. Service Credits'),
      ...d.creditTiers.map((t, i) => row(`Tier ${i + 1}`, `Below ${v(t.uptimeBelow)}% → ${v(t.creditPct)}% credit`)),
      row('Monthly Cap', d.creditCapPct ? `${d.creditCapPct}%` : '—'),
      row('Claim Notice Period', d.creditClaimDays ? `${d.creditClaimDays} days` : '—'),
      row('Sole Remedy', yn(d.creditsSoleRemedy)),
    ] : []),
    sep(),
    h2('11. Legal and Signing'),
    row('Governing Law', d.governingLaw),
    row('Dispute Forum', d.disputeForum),
    ...(d.disputeForum === 'South African courts' ? [row('Jurisdiction', d.jurisdictionCity)] : []),
    row('Signature Method', d.signatureMethod),
    ...(d.signatureMethod === 'Platform signature' ? [row('Signing Order', d.signingOrder)] : []),
    row('Signatories', d.signatories.filter((s) => s.name).map((s) => `${s.name} (${s.title})`).join(', ') || '—'),
    sep(),
    disclaimer(),
  ])
}
