/**
 * docxBuilders.ts
 * Generates real .docx files using the `docx` library.
 * Each builder returns a Promise<Blob> with the correct MIME type.
 *
 * These replace the RTF builders which were renamed .docx but were
 * actually RTF format — causing "unreadable content" warnings in Word.
 */
import {
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  TextRun,
  AlignmentType,
  BorderStyle,
} from 'docx'

import type { NdaWizardData } from '../pages/user-dashboard/NdaWizardModal'
import type { EmploymentWizardData } from '../pages/user-dashboard/EmploymentWizardModal'
import type { PrivacyPolicyWizardData } from '../pages/user-dashboard/PrivacyPolicyWizardModal'
import type { FounderAgreementWizardData } from '../pages/user-dashboard/FounderAgreementWizardModal'
import type { ServiceAgreementWizardData } from '../pages/user-dashboard/ServiceAgreementWizardModal'

// ── Shared helpers ────────────────────────────────────────────────────────────

const fmtDate = (d: string | null) =>
  d ? new Date(d).toLocaleDateString('en-ZA') : new Date().toLocaleDateString('en-ZA')

const val = (v: string | undefined | null) => v || '—'
const yn  = (v: boolean) => (v ? 'Yes' : 'No')

/** Bold heading paragraph */
const h1 = (text: string) =>
  new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun({ text, bold: true, size: 28 })] })

const h2 = (text: string) =>
  new Paragraph({ heading: HeadingLevel.HEADING_2, children: [new TextRun({ text, bold: true, size: 24 })] })

/** Label: value row */
const row = (label: string, value: string) =>
  new Paragraph({
    children: [
      new TextRun({ text: `${label}: `, bold: true }),
      new TextRun({ text: val(value) }),
    ],
    indent: { left: 360 },
  })

/** Thin horizontal separator */
const sep = () =>
  new Paragraph({
    border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: 'AAAAAA' } },
    spacing: { before: 120, after: 120 },
    children: [],
  })

/** Italic disclaimer footer */
const disclaimer = () =>
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { before: 400 },
    children: [
      new TextRun({
        text: 'DISCLAIMER: This document is generated for reference purposes only. It does not constitute legal advice. Consult a qualified attorney.',
        italics: true,
        size: 18,
        color: '888888',
      }),
    ],
  })

const pack = (sections: Paragraph[]) =>
  Packer.toBlob(
    new Document({
      sections: [{ properties: {}, children: sections }],
      creator: 'The Startup Legal',
    }),
  )

// ── NDA ───────────────────────────────────────────────────────────────────────

export async function buildNdaDocx(data: NdaWizardData, completedAt: string | null): Promise<Blob> {
  const fmtAddr = (a: NdaWizardData['party_a']['address']) =>
    [a.street_number, a.building, a.street_name, a.suburb, a.city, a.province, a.postal_code, a.country].filter(Boolean).join(', ')

  return pack([
    h1('NON-DISCLOSURE AGREEMENT'),
    row('Date', fmtDate(completedAt)),
    row('Generated by', 'The Startup Legal'),
    sep(),
    h2('1. Parties'),
    row('Agreement Type', data.agreement_type),
    sep(),
    h2('Party A'),
    row('Type', data.party_a.entity_type),
    row('Legal Name', data.party_a.legal_name || data.party_a.full_names),
    row('Registration No.', data.party_a.reg_number),
    row('Address', fmtAddr(data.party_a.address)),
    row('Email', data.party_a.email),
    row('Signatory', `${data.party_a.signatory_name} (${data.party_a.signatory_capacity})`),
    sep(),
    h2('Party B'),
    row('Type', data.party_b.entity_type),
    row('Legal Name', data.party_b.legal_name || data.party_b.full_names),
    row('Registration No.', data.party_b.reg_number),
    row('Address', fmtAddr(data.party_b.address)),
    row('Email', data.party_b.email),
    row('Signatory', `${data.party_b.signatory_name} (${data.party_b.signatory_capacity})`),
    sep(),
    h2('2. Purpose & Scope'),
    row('Purpose', data.purpose),
    row('CI Definition', data.ci_definition),
    row('Must be marked confidential', yn(data.marking_required)),
    sep(),
    h2('3. Obligations'),
    row('Duration', `${data.duration_years} years, from ${data.duration_start}`),
    row('Return / Destroy', data.return_or_destroy),
    row('Archival copy', yn(data.archival_copy)),
    row('Non-solicitation', data.non_solicit ? `Yes (${data.non_solicit_months} months)` : 'No'),
    sep(),
    h2('4. Legal + Signing'),
    row('Governing Law', data.governing_law),
    row('Dispute Forum', data.dispute_forum),
    row('Signature Method', data.signature_method),
    row('Signing Order', data.signing_order),
    sep(),
    disclaimer(),
  ])
}

// ── Employment Offer Letter ───────────────────────────────────────────────────

export async function buildEmploymentDocx(d: EmploymentWizardData, completedAt: string | null): Promise<Blob> {
  const salary = d.salaryAmount ? `R${Number(d.salaryAmount).toLocaleString('en-ZA')} ${d.salaryFrequency}` : '—'
  return pack([
    h1('EMPLOYMENT OFFER LETTER'),
    row('Date', fmtDate(completedAt)),
    row('Generated by', 'The Startup Legal'),
    sep(),
    h2('1. Employer Details'),
    row('Company Name', d.companyName),
    row('Registration No.', d.companyReg),
    row('Address', d.employerAddress),
    row('Contact Person', d.employerContactPerson),
    row('Email', d.employerEmail),
    sep(),
    h2('2. Employee Details'),
    row('Full Name', d.employeeFullName),
    row('ID / Passport', d.employeeIdNumber),
    row('Address', d.employeeAddress),
    row('Email', d.employeeEmail),
    row('Phone', d.employeePhone),
    sep(),
    h2('3. Employment Information'),
    row('Job Title', d.jobTitle),
    row('Department', d.department),
    row('Employment Type', d.employmentType),
    row('Start Date', d.startDate),
    row('Probation Period', d.probationPeriod),
    row('Working Hours', d.workingHours),
    row('Work Location', d.workLocation),
    sep(),
    h2('4. Salary & Benefits'),
    row('Salary', salary),
    row('Bonuses', d.bonuses),
    row('Leave Entitlement', d.leaveEntitlement),
    row('Medical Benefits', d.medicalBenefits),
    row('Pension', d.pension),
    row('Other Benefits', d.otherBenefits),
    sep(),
    h2('5. Contract Terms'),
    row('Notice Period', d.noticePeriod),
    row('Governing Law', d.governingLaw),
    row('Confidentiality Clause', yn(d.confidentialityClause)),
    row('Intellectual Property Clause', yn(d.intellectualPropertyClause)),
    row('Non-Compete Clause', yn(d.nonCompeteClause)),
    sep(),
    disclaimer(),
  ])
}

// ── Privacy Policy ────────────────────────────────────────────────────────────

export async function buildPrivacyPolicyDocx(d: PrivacyPolicyWizardData, completedAt: string | null): Promise<Blob> {
  return pack([
    h1('PRIVACY POLICY (POPIA COMPLIANT)'),
    row('Date', fmtDate(completedAt)),
    row('Generated by', 'The Startup Legal'),
    sep(),
    h2('1. Business Information'),
    row('Company Name', d.companyName),
    row('Website', d.website),
    row('Business Email', d.businessEmail),
    row('Contact Number', d.contactNumber),
    row('Physical Address', d.physicalAddress),
    sep(),
    h2('2. Information Collected'),
    row('Personal Information', yn(d.collectsPersonalInfo)),
    row('Contact Details', yn(d.collectsContactDetails)),
    row('Payment Information', yn(d.collectsPaymentInfo)),
    row('Technical Information', yn(d.collectsTechnicalInfo)),
    row('Cookies', yn(d.collectsCookies)),
    sep(),
    h2('3. Purpose of Collection'),
    row('Service Delivery', yn(d.purposeServiceDelivery)),
    row('Marketing', yn(d.purposeMarketing)),
    row('Analytics', yn(d.purposeAnalytics)),
    row('Customer Support', yn(d.purposeCustomerSupport)),
    row('Legal Compliance', yn(d.purposeLegalCompliance)),
    sep(),
    h2('4. Data Sharing'),
    row('Third-party Providers', yn(d.sharesThirdPartyProviders)),
    row('Payment Gateways', yn(d.sharesPaymentGateways)),
    row('Marketing Platforms', yn(d.sharesMarketingPlatforms)),
    row('Government Authorities', yn(d.sharesGovernmentAuthorities)),
    sep(),
    h2('5. User Rights'),
    row('Right to Access', yn(d.rightAccess)),
    row('Right to Correction', yn(d.rightCorrection)),
    row('Right to Deletion', yn(d.rightDeletion)),
    row('Right to Object', yn(d.rightObjection)),
    row('Right to Data Portability', yn(d.rightDataPortability)),
    sep(),
    h2('6. Security & Retention'),
    row('Data Storage', d.dataStorage),
    row('Retention Period', d.retentionPeriod),
    row('Security Measures', d.securityMeasures),
    sep(),
    disclaimer(),
  ])
}

// ── Founder Agreement ─────────────────────────────────────────────────────────

export async function buildFounderAgreementDocx(d: FounderAgreementWizardData, completedAt: string | null): Promise<Blob> {
  const founderRows = d.founders.flatMap((f, i) => [
    h2(`Founder ${i + 1}`),
    row('Full names', f.fullNames),
    row('Identity number', f.idNumber),
    row('Role', f.role),
    row('Time commitment', f.commitment),
    row('Equity', f.equityPct ? `${f.equityPct}%` : '—'),
    row('Capital contributed', f.capital),
  ])
  const priorIpRows = d.priorIpNil
    ? [row('Pre-existing IP', 'Nothing to declare')]
    : d.priorIp.flatMap((p, i) => [
        h2(`Prior IP ${i + 1}`),
        row('Founder', p.founder),
        row('Description', p.description),
        row('Date created', p.dateCreated),
        row('Treatment', p.treatment),
      ])
  const digitalRows = d.digitalAssets.flatMap((a, i) => [
    h2(`Digital asset ${i + 1}`),
    row('Asset', a.asset),
    row('Current holder', a.currentHolder),
    row('Transfer date', a.transferDate),
  ])
  const sigRows = d.signatories.map((s, i) => row(`Signatory ${i + 1}`, `${val(s.name)} (${val(s.capacity)})`))
  return pack([
    h1("FOUNDERS' AGREEMENT & IP ASSIGNMENT"),
    row('Date', fmtDate(completedAt)),
    row('Generated by', 'The Startup Legal'),
    sep(),
    h2('1. Company Status'),
    row('Incorporated', d.isIncorporated),
    ...(d.isIncorporated === 'Yes'
      ? [row('Company Name', d.companyName)]
      : [row('Intended name', d.intendedName), row('Target incorporation', d.targetIncorporation)]),
    sep(),
    h2('2. Founders & Equity'),
    ...founderRows,
    sep(),
    h2('3. Vesting'),
    row('Vesting applies', d.vestingApplies),
    ...(d.vestingApplies === 'Yes' ? [
      row('Vesting period (months)', d.vestingMonths),
      row('Cliff (months)', d.cliffMonths),
      row('Frequency', d.vestingFrequency),
      row('Acceleration', d.acceleration),
      row('Good leaver', d.goodLeaver.join('; ')),
      row('Bad leaver consequence', d.badLeaverEffect),
    ] : []),
    sep(),
    h2('4. Decisions & Roles'),
    row('Decision model', d.decisionModel),
    row('Reserved matters', d.reservedMatters.join('; ')),
    ...(d.reservedMatters.includes('Take on debt above a threshold') ? [row('Debt threshold', d.debtThreshold)] : []),
    row('Removal process', d.removalProcess),
    row('Departure role', d.departureRole),
    sep(),
    h2('5. Intellectual Property'),
    row('IP assignment', 'Yes — assignment applies'),
    row('Assignment covers pre-incorporation work', d.ipPreIncorporation),
    ...priorIpRows,
    row('Publicly funded', d.publiclyFunded),
    row('Created while employed elsewhere', d.createdAtEmployer),
    ...digitalRows,
    sep(),
    h2('6. Protections & Legal'),
    row('Confidentiality', d.confidentiality),
    row('Non-solicitation', d.nonSolicit),
    row('Restraint of trade', d.restraint),
    ...(d.restraint === 'Yes' ? [row('Restraint duration (months)', d.restraintMonths), row('Restraint area', d.restraintArea)] : []),
    row('Deadlock mechanism', d.deadlock),
    row('Dispute resolution', d.disputeForum),
    row('Governing law', d.governingLaw),
    ...sigRows,
    sep(),
    disclaimer(),
  ])
}

// ── Service Agreement ─────────────────────────────────────────────────────────

export async function buildServiceAgreementDocx(d: ServiceAgreementWizardData, completedAt: string | null): Promise<Blob> {
  return pack([
    h1('SERVICE AGREEMENT'),
    row('Date', fmtDate(completedAt)),
    row('Generated by', 'The Startup Legal'),
    sep(),
    h2('1. Parties'),
    h2('Service Provider'),
    row('Legal Name', d.providerName),
    row('Registration No.', d.providerReg),
    row('Address', d.providerAddress),
    h2('Client'),
    row('Legal Name', d.clientName),
    row('Registration No.', d.clientReg),
    row('Address', d.clientAddress),
    row('Contact Name', d.contactName),
    row('Contact Email', d.contactEmail),
    row('Contact Phone', d.contactPhone),
    sep(),
    h2('2. Services'),
    row('Services Description', d.servicesDescription),
    row('Scope of Work', d.scopeOfWork),
    row('Deliverables', d.deliverables),
    sep(),
    h2('3. Fees & Pricing'),
    row('Pricing', d.pricing),
    row('Payment Terms', d.paymentTerms),
    row('Billing Frequency', d.billingFrequency),
    sep(),
    h2('4. Service Levels'),
    row('Availability', d.availability),
    row('Response Time', d.responseTime),
    row('Resolution Time', d.resolutionTime),
    row('Support Hours', d.supportHours),
    sep(),
    h2('5. Responsibilities'),
    row('Provider Responsibilities', d.providerResponsibilities),
    row('Client Responsibilities', d.clientResponsibilities),
    sep(),
    h2('6. Term & Termination'),
    row('Start Date', d.startDate),
    row('End Date', d.endDate),
    row('Renewal', d.renewal),
    row('Termination Notice', d.terminationNotice),
    sep(),
    h2('7. Legal'),
    row('Confidentiality', d.confidentiality),
    row('Liability', d.liability),
    row('Governing Law', d.governingLaw),
    row('Jurisdiction', d.jurisdiction),
    sep(),
    disclaimer(),
  ])
}
