/**
 * docxBuilders.ts
 * Generates real .docx files using the `docx` library.
 * Each builder returns a Promise<Blob> with the correct MIME type.
 *
 * These replace the RTF builders which were renamed .docx but were
 * actually RTF format — causing "unreadable content" warnings in Word.
 */
import {
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  TextRun,
  AlignmentType,
  BorderStyle,
} from 'docx'

import type { NdaWizardData } from '../pages/user-dashboard/NdaWizardModal'
import type { EmploymentWizardData } from '../pages/user-dashboard/EmploymentWizardModal'
import type { PrivacyPolicyWizardData } from '../pages/user-dashboard/PrivacyPolicyWizardModal'
import type { FounderAgreementWizardData } from '../pages/user-dashboard/FounderAgreementWizardModal'
import type { ServiceAgreementWizardData } from '../pages/user-dashboard/ServiceAgreementWizardModal'
import type { SlaWizardData } from '../pages/user-dashboard/SlaWizardModal'
import type { ShareCertificateData } from '../pages/user-dashboard/ShareCertificateWizard'
import type { BoardResolutionData } from '../pages/user-dashboard/BoardResolutionWizard'
import type { FounderEmploymentData } from '../pages/user-dashboard/FounderEmploymentWizard'
import type { WebsiteTermsData } from '../pages/user-dashboard/WebsiteTermsWizard'
import type { POPIARecordsData } from '../pages/user-dashboard/POPIARecordsWizard'
import type { RefundsPolicyData } from '../pages/user-dashboard/RefundsPolicyWizard'



// ── Shared helpers ────────────────────────────────────────────────────────────

const fmtDate = (d: string | null) =>
  d ? new Date(d).toLocaleDateString('en-ZA') : new Date().toLocaleDateString('en-ZA')

const val = (v: string | undefined | null) => v || '—'
const yn  = (v: boolean) => (v ? 'Yes' : 'No')

/** Bold heading paragraph */
const h1 = (text: string) =>
  new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun({ text, bold: true, size: 28 })] })

const h2 = (text: string) =>
  new Paragraph({ heading: HeadingLevel.HEADING_2, children: [new TextRun({ text, bold: true, size: 24 })] })

/** Label: value row */
const row = (label: string, value: string) =>
  new Paragraph({
    children: [
      new TextRun({ text: `${label}: `, bold: true }),
      new TextRun({ text: val(value) }),
    ],
    indent: { left: 360 },
  })

/** Thin horizontal separator */
const sep = () =>
  new Paragraph({
    border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: 'AAAAAA' } },
    spacing: { before: 120, after: 120 },
    children: [],
  })

/** Italic disclaimer footer */
const disclaimer = () =>
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { before: 400 },
    children: [
      new TextRun({
        text: 'DISCLAIMER: This document is generated for reference purposes only. It does not constitute legal advice. Consult a qualified attorney.',
        italics: true,
        size: 18,
        color: '888888',
      }),
    ],
  })

const pack = (sections: Paragraph[]) =>
  Packer.toBlob(
    new Document({
      sections: [{ properties: {}, children: sections }],
      creator: 'The Startup Legal',
    }),
  )

// ── NDA ───────────────────────────────────────────────────────────────────────

export async function buildNdaDocx(data: NdaWizardData, completedAt: string | null): Promise<Blob> {
  const fmtAddr = (a: NdaWizardData['party_a']['address']) =>
    [a.street_number, a.building, a.street_name, a.suburb, a.city, a.province, a.postal_code, a.country].filter(Boolean).join(', ')

  return pack([
    h1('NON-DISCLOSURE AGREEMENT'),
    row('Date', fmtDate(completedAt)),
    row('Generated by', 'The Startup Legal'),
    sep(),
    h2('1. Parties'),
    row('Agreement Type', data.agreement_type),
    sep(),
    h2('Party A'),
    row('Type', data.party_a.entity_type),
    row('Legal Name', data.party_a.legal_name || data.party_a.full_names),
    row('Registration No.', data.party_a.reg_number),
    row('Address', fmtAddr(data.party_a.address)),
    row('Email', data.party_a.email),
    row('Signatory', `${data.party_a.signatory_name} (${data.party_a.signatory_capacity})`),
    sep(),
    h2('Party B'),
    row('Type', data.party_b.entity_type),
    row('Legal Name', data.party_b.legal_name || data.party_b.full_names),
    row('Registration No.', data.party_b.reg_number),
    row('Address', fmtAddr(data.party_b.address)),
    row('Email', data.party_b.email),
    row('Signatory', `${data.party_b.signatory_name} (${data.party_b.signatory_capacity})`),
    sep(),
    h2('2. Purpose & Scope'),
    row('Purpose', data.purpose),
    row('CI Definition', data.ci_definition),
    ...(data.ci_definition === 'Specified categories only'
      ? [row('Categories', data.ci_categories.length ? data.ci_categories.join(', ') : '—')]
      : []),
    ...(data.ci_definition === 'Broad with standard exclusions'
      ? [row('Standard Exclusions', data.ci_exclusions.length ? data.ci_exclusions.join(', ') : '—')]
      : []),
    row('Information must be marked confidential', yn(data.marking_required)),
    sep(),
    h2('3. Obligations'),
    row('Duration', `${data.duration_years} years, from ${data.duration_start}`),
    row('Return / Destroy', data.return_or_destroy),
    row('Who may receive information', data.permitted_recipients.length ? data.permitted_recipients.join(', ') : '—'),
    row('Archival copy', yn(data.archival_copy)),
    row('Non-solicitation', data.non_solicit ? `Yes (${data.non_solicit_months} months)` : 'No'),
    sep(),
    h2('4. Legal + Signing'),
    row('Governing Law', data.governing_law),
    row('Dispute Forum', data.dispute_forum),
    row('Your address for notices', fmtAddr(data.domicilium_a)),
    row('Their address for notices', fmtAddr(data.domicilium_b)),
    row('Signature Method', data.signature_method),
    row('Signing Order', data.signing_order),
    sep(),
    disclaimer(),
  ])
}

// ── Employment Offer Letter ───────────────────────────────────────────────────

export async function buildEmploymentDocx(d: EmploymentWizardData, completedAt: string | null): Promise<Blob> {
  const salary = d.salary_amount ? `R${Number(d.salary_amount).toLocaleString('en-ZA')} ${d.salary_period}` : '—'
  return pack([
    h1('EMPLOYMENT OFFER LETTER'),
    row('Date', fmtDate(completedAt)),
    row('Generated by', 'The Startup Legal'),
    sep(),
    h2('1. Employer Details'),
    row('Employer', d.employer_name),
    sep(),
    h2('2. Candidate and Role'),
    row('Candidate Name', d['candidate.full_names']),
    row('Candidate Email', d['candidate.email']),
    row('Job Title', d.job_title),
    row('Reports To', d.reports_to),
    row('Start Date', d.start_date),
    row('Work Location', d.work_location),
    sep(),
    h2('3. Package'),
    row('Salary', salary),
    row('Benefits', d.benefits.join(', ') || 'None'),
    row('Employer Contribution', d.benefits_detail || '—'),
    row('Probation (months)', d.probation_months || '—'),
    row('Restraint Will Apply', yn(d.restraint_flag === true)),
    sep(),
    h2('4. Conditions'),
    row('Offer Conditions', d.conditions.join(', ')),
    row('Medical Assessment Justification', d.medical_justification || '—'),
    row('Work Authorisation Type', d.work_permit_type || 'Not required'),
    row('Work Authorisation Expiry', d.work_permit_expiry || '—'),
    row('Offer Expiry', d.offer_expiry),
    sep(),
    disclaimer(),
  ])
}

// ── Privacy Policy ────────────────────────────────────────────────────────────

export async function buildPrivacyPolicyDocx(d: PrivacyPolicyWizardData, completedAt: string | null): Promise<Blob> {
  const purposeRows = d.purposes.flatMap((purpose, index) => [
    h2(`Purpose ${index + 1}`),
    row('Purpose', purpose.purpose),
    row('Categories', purpose.categories),
    row('Lawful Basis', purpose.basis),
    row('LI Statement', purpose.liStatement),
  ])

  const retentionRows = d.retention.flatMap((retention, index) => [
    h2(`Retention ${index + 1}`),
    row('Category', retention.category),
    row('Period', retention.period),
    row('Reason', retention.reason),
  ])

  const thirdPartyRows = d.thirdParties.flatMap((party, index) => [
    h2(`Third Party ${index + 1}`),
    row('Name', party.name),
    row('Purpose', party.purpose),
    row('Country', party.country),
  ])

  const cookieRows = d.cookies.flatMap((cookie, index) => [
    h2(`Cookie ${index + 1}`),
    row('Name', cookie.name),
    row('Purpose', cookie.purpose),
    row('Duration', cookie.duration),
    row('Necessary', cookie.necessary),
  ])

  return pack([
    h1('PRIVACY & COOKIES POLICY'),
    row('Date', fmtDate(completedAt)),
    row('Generated by', 'The Startup Legal'),
    sep(),
    h2('1. Who you are'),
    row('Responsible Party', d.responsibleParty),
    row('Confirmed', yn(d.responsiblePartyConfirmed)),
    row('Information Officer', d.officerFullNames),
    row('Officer Identity No.', d.officerIdNumber),
    row('Officer Email', d.officerEmail),
    row('Officer Address', d.officerAddress),
    row('Officer Telephone', d.officerPhone),
    row('Privacy Email', d.privacyEmail),
    row('Domains', d.domains.filter(Boolean).join(', ')),
    sep(),
    h2('2. What you collect'),
    row('PI Categories', d.piCategories.join(', ')),
    row('Special PI', d.specialPi.join(', ') || 'None'),
    row('Special PI Basis', d.specialPiBasis),
    row('Children Data', yn(d.childrenData)),
    row('Children Consent', d.childrenConsent),
    sep(),
    h2('3. Why & basis'),
    ...purposeRows,
    ...retentionRows,
    sep(),
    h2('4. Who else sees it'),
    ...thirdPartyRows,
    row('Cross-border Transfers', yn(d.crossBorder)),
    row('Transfer Countries', d.crossBorderCountries.join(', ')),
    row('Transfer Basis', d.transferBasis),
    row('Direct Marketing', yn(d.directMarketing)),
    sep(),
    h2('5. Cookies'),
    ...cookieRows,
    row('Cookie Consent', d.cookieConsent),
    row('Analytics Provider', d.analyticsProvider),
    sep(),
    h2('6. Publication'),
    row('DSR Channel', d.dsrChannel),
    row('DSR Days', d.dsrDays),
    row('Security Summary', d.securitySummary.join(', ')),
    row('Effective Date', d.effectiveDate),
    row('Automated Decisions', yn(d.automatedDecisions)),
    sep(),
    disclaimer(),
  ])
}

// ── Founder Agreement ─────────────────────────────────────────────────────────

export async function buildFounderAgreementDocx(d: FounderAgreementWizardData, completedAt: string | null): Promise<Blob> {
  const founderRows = d.founders.flatMap((f, i) => [
    h2(`Founder ${i + 1}`),
    row('Full names', f.fullNames),
    row('Identity number', f.idNumber),
    row('Role', f.role),
    row('Time commitment', f.commitment),
    row('Equity', f.equityPct ? `${f.equityPct}%` : '—'),
    row('Capital contributed', f.capital),
  ])
  const priorIpRows = d.priorIpNil
    ? [row('Pre-existing IP', 'Nothing to declare')]
    : d.priorIp.flatMap((p, i) => [
        h2(`Prior IP ${i + 1}`),
        row('Founder', p.founder),
        row('Description', p.description),
        row('Date created', p.dateCreated),
        row('Treatment', p.treatment),
      ])
  const digitalRows = d.digitalAssets.flatMap((a, i) => [
    h2(`Digital asset ${i + 1}`),
    row('Asset', a.asset),
    row('Current holder', a.currentHolder),
    row('Transfer date', a.transferDate),
  ])
  const sigRows = d.signatories.map((s, i) => row(`Signatory ${i + 1}`, `${val(s.name)} (${val(s.capacity)})`))
  return pack([
    h1("FOUNDERS' AGREEMENT & IP ASSIGNMENT"),
    row('Date', fmtDate(completedAt)),
    row('Generated by', 'The Startup Legal'),
    sep(),
    h2('1. Company Status'),
    row('Incorporated', d.isIncorporated),
    ...(d.isIncorporated === 'Yes'
      ? [row('Company Name', d.companyName)]
      : [row('Intended name', d.intendedName), row('Target incorporation', d.targetIncorporation)]),
    sep(),
    h2('2. Founders & Equity'),
    ...founderRows,
    sep(),
    h2('3. Vesting'),
    row('Vesting applies', d.vestingApplies),
    ...(d.vestingApplies === 'Yes' ? [
      row('Vesting period (months)', d.vestingMonths),
      row('Cliff (months)', d.cliffMonths),
      row('Frequency', d.vestingFrequency),
      row('Acceleration', d.acceleration),
      row('Good leaver', d.goodLeaver.join('; ')),
      row('Bad leaver consequence', d.badLeaverEffect),
    ] : []),
    sep(),
    h2('4. Decisions & Roles'),
    row('Decision model', d.decisionModel),
    row('Reserved matters', d.reservedMatters.join('; ')),
    ...(d.reservedMatters.includes('Take on debt above a threshold') ? [row('Debt threshold', d.debtThreshold)] : []),
    row('Removal process', d.removalProcess),
    row('Departure role', d.departureRole),
    sep(),
    h2('5. Intellectual Property'),
    row('IP assignment', 'Yes — assignment applies'),
    row('Assignment covers work created before incorporation', d.ipPreIncorporation),
    ...priorIpRows,
    row('Publicly funded', d.publiclyFunded),
    row('Created while employed elsewhere', d.createdAtEmployer),
    ...digitalRows,
    sep(),
    h2('6. Protections & Legal'),
    row('Confidentiality', d.confidentiality),
    row('Non-solicitation', d.nonSolicit),
    row('Restraint of trade', d.restraint),
    ...(d.restraint === 'Yes' ? [row('Restraint duration (months)', d.restraintMonths), row('Restraint area', d.restraintArea)] : []),
    row('Deadlock mechanism', d.deadlock),
    row('Dispute resolution', d.disputeForum),
    row('Governing law', d.governingLaw),
    ...sigRows,
    sep(),
    disclaimer(),
  ])
}

// ── Service Agreement ─────────────────────────────────────────────────────────

export async function buildServiceAgreementDocx(d: ServiceAgreementWizardData, completedAt: string | null): Promise<Blob> {
  return pack([
    h1('SERVICE AGREEMENT'),
    row('Date', fmtDate(completedAt)),
    row('Generated by', 'The Startup Legal'),
    sep(),
    h2('1. Parties'),
    h2('Service Provider'),
    row('Legal Name', d.providerName),
    row('Registration No.', d.providerReg),
    row('Address', d.providerAddress),
    h2('Client'),
    row('Legal Name', d.clientName),
    row('Registration No.', d.clientReg),
    row('Address', d.clientAddress),
    row('Contact Name', d.contactName),
    row('Contact Email', d.contactEmail),
    row('Contact Phone', d.contactPhone),
    sep(),
    h2('2. Services'),
    row('Services Description', d.servicesDescription),
    row('Scope of Work', d.scopeOfWork),
    row('Deliverables', d.deliverables),
    sep(),
    h2('3. Fees & Pricing'),
    row('Pricing', d.pricing),
    row('Payment Terms', d.paymentTerms),
    row('Billing Frequency', d.billingFrequency),
    sep(),
    h2('4. Service Levels'),
    row('Availability', d.availability),
    row('Response Time', d.responseTime),
    row('Resolution Time', d.resolutionTime),
    row('Support Hours', d.supportHours),
    sep(),
    h2('5. Responsibilities'),
    row('Provider Responsibilities', d.providerResponsibilities),
    row('Client Responsibilities', d.clientResponsibilities),
    sep(),
    h2('6. Term & Termination'),
    row('Start Date', d.startDate),
    row('End Date', d.endDate),
    row('Renewal', d.renewal),
    row('Termination Notice', d.terminationNotice),
    sep(),
    h2('7. Legal'),
    row('Confidentiality', d.confidentiality),
    row('Liability', d.liability),
    row('Governing Law', d.governingLaw),
    row('Jurisdiction', d.jurisdiction),
    sep(),
    disclaimer(),
  ])
}

// ── Service Level Agreement (SLA) ─────────────────────────────────────────────

export async function buildSlaDocx(d: SlaWizardData, completedAt: string | null): Promise<Blob> {
  const v = (s: string | undefined | null) => s || '—'
  const yn = (b: boolean) => (b ? 'Yes' : 'No')

  return pack([
    h1('SERVICE LEVEL AGREEMENT (SLA)'),
    row('Date', fmtDate(completedAt)),
    row('Generated by', 'The Startup Legal'),
    sep(),
    h2('1. Parties'),
    h2('Service Provider'),
    row('Name', d.provider?.legalName || d.provider?.fullNames || d.providerName),
    ...(d.provider?.regNumber || d.providerReg ? [row('Reg No.', d.provider?.regNumber || d.providerReg)] : []),
    ...(d.provider?.email || d.providerEmail ? [row('Email', d.provider?.email || d.providerEmail)] : []),
    h2('Customer'),
    row('Name', d.customer?.legalName || d.customer?.fullNames || d.customerName),
    ...(d.customer?.regNumber || d.customerReg ? [row('Reg No.', d.customer?.regNumber || d.customerReg)] : []),
    ...(d.customer?.email || d.customerEmail ? [row('Email', d.customer?.email || d.customerEmail)] : []),
    sep(),
    h2('2. Agreement Details'),
    row('Service Description', d.serviceDescription),
    row('Start Date', d.startDate),
    row('Term', d.termType),
    ...(d.termType === 'Fixed end date' ? [row('End Date', d.endDate)] : []),
    sep(),
    h2('3. Modules'),
    row('Selected', d.modules.length > 0 ? d.modules.join(', ') : '—'),
    ...(d.modules.includes('Availability') ? [
      sep(),
      h2('4. Availability'),
      row('Uptime Target', d.uptimeTarget ? `${d.uptimeTarget}%` : '—'),
      row('Measurement Period', d.uptimePeriod),
      row('Exclusions', d.uptimeExclusions.join(', ') || '—'),
    ] : []),
    ...(d.modules.includes('Support') ? [
      sep(),
      h2('5. Support'),
      row('Support Hours', d.supportHours),
      ...(d.supportHours === 'Custom' ? [row('Custom Hours', d.supportHoursCustom)] : []),
      row('Support Channels', d.supportChannels.join(', ') || '—'),
    ] : []),
    ...(d.modules.includes('Incident response') ? [
      sep(),
      h2('6. Incident Response'),
      row('Severity Model', yn(d.useSeverityModel)),
      ...(d.useSeverityModel
        ? d.severityTargets.map((t) => row(t.severity, `Response: ${v(t.responseTarget)} | Resolution: ${v(t.resolutionTarget)}`))
        : [row('Incident Handling Description', v(d.incidentNarrative))]),
      row('Escalation Contacts', d.escalationContacts.map((c) => `${c.name} (${c.role}) ${c.email}`).join('; ') || '—'),
    ] : []),
    ...(d.modules.includes('Maintenance') ? [
      sep(),
      h2('7. Maintenance'),
      row('Planned Window', d.maintenanceWindow),
      row('Notice Period', d.maintenanceNoticeHours ? `${d.maintenanceNoticeHours} hours` : '—'),
      row('Emergency Permitted', yn(d.emergencyMaintenance)),
    ] : []),
    ...(d.modules.includes('Backups and restore') ? [
      sep(),
      h2('8. Backups and Restore'),
      row('Backup Frequency', d.backupFrequency),
      row('RTO', d.rtoHours ? `${d.rtoHours} hours` : '—'),
      row('RPO', d.rpoHours ? `${d.rpoHours} hours` : '—'),
      row('Retention', d.backupRetentionDays ? `${d.backupRetentionDays} days` : '—'),
    ] : []),
    ...(d.modules.includes('Security') ? [
      sep(),
      h2('9. Security'),
      row('Commitments', d.securityCommitments.join(', ') || '—'),
      row('Breach Notification', d.breachNoticeHours ? `${d.breachNoticeHours} hours` : '—'),
    ] : []),
    ...(d.modules.includes('Service credits') ? [
      sep(),
      h2('10. Service Credits'),
      ...d.creditTiers.map((t, i) => row(`Tier ${i + 1}`, `Below ${v(t.uptimeBelow)}% → ${v(t.creditPct)}% credit`)),
      row('Monthly Cap', d.creditCapPct ? `${d.creditCapPct}%` : '—'),
      row('Claim Notice Period', d.creditClaimDays ? `${d.creditClaimDays} days` : '—'),
      row('Sole Remedy', yn(d.creditsSoleRemedy)),
    ] : []),
    sep(),
    h2('11. Legal and Signing'),
    row('Governing Law', d.governingLaw),
    row('Dispute Forum', d.disputeForum),
    ...(d.disputeForum === 'South African courts' ? [row('Jurisdiction', d.jurisdictionCity)] : []),
    row('Signatories', d.signatories.filter((s) => s.name).map((s) => `${s.name} (${s.title})`).join(', ') || '—'),
    sep(),
    disclaimer(),
  ])
}

export async function buildShareCertificateDocx(data: ShareCertificateData, completedAt: string | null): Promise<Blob> {
  const shareholder = data.shareholder === '__new' ? data.newPartyName : data.shareholder
  const consideration = data.considerationType === 'cash'
    ? `Cash: R ${data.amount || '—'}`
    : `Non-cash: ${data.description || '—'}`
  return pack([
    h1('SHARE CERTIFICATE'),
    row('Certificate number', data.certNumber),
    row('Date of issue', data.issueDate || fmtDate(completedAt)),
    row('Company', data.company),
    sep(),
    h2('Share issue'),
    row('Shareholder', shareholder),
    row('Share class', data.shareClass),
    row('Number of shares', data.shareCount),
    row('Consideration', consideration),
    row('Fully paid', data.fullyPaid === 'yes' ? 'Yes' : 'No - certificate records the shares as not fully paid.'),
    sep(),
    h2('Authorisation'),
    row('Authorising resolution', data.resolution === '__upload' ? `Uploaded: ${data.uploadedResolutionName || 'signed resolution'}` : data.resolution),
    row('Signatories', data.signatories.join(', ') || '—'),
    sep(),
    disclaimer(),
  ])
}

export async function buildBoardResolutionDocx(data: BoardResolutionData, completedAt: string | null): Promise<Blob> {
  return pack([
    h1('BOARD RESOLUTION'),
    row('Company', data.company),
    row('Resolution type', data.resolutionType),
    row('Date', data.meetingDate || fmtDate(completedAt)),
    sep(),
    h2(data.subject),
    new Paragraph({ children: [new TextRun({ text: data.wording || '—' })] }),
    sep(),
    h2('Meeting record'),
    row('Passed at', data.meetingType === 'rr' ? 'Round robin' : 'A meeting'),
    ...(data.meetingType === 'meeting' ? [row('Time', data.meetingTime), row('Venue', data.meetingVenue), row('Chairperson', data.chairperson)] : []),
    row('Present', data.attendees.join(', ') || '—'),
    row('Votes', `For: ${data.votesFor}; Against: ${data.votesAgainst}; Abstained: ${data.votesAbstain}`),
    sep(),
    h2('Signatories'),
    ...data.signatories.map((name) => new Paragraph({ children: [new TextRun({ text: `${name}  ____________________` })], spacing: { after: 220 } })),
    sep(),
    disclaimer(),
  ])
}

export async function buildFounderEmploymentDocx(data: FounderEmploymentData, completedAt: string | null): Promise<Blob> {
  const address = [data.street, data.suburb, data.city, data.province, data.postalCode].filter(Boolean).join(', ')
  return pack([
    h1('FOUNDER EMPLOYMENT CONTRACT'),
    row('Company', data.company),
    row('Date', fmtDate(completedAt)),
    sep(),
    h2('Role'),
    row('Founder', data.fullNames),
    row('Identity number', data.idNumber),
    row('Email', data.email),
    ...(data.phone ? [row('Telephone', data.phone)] : []),
    row('Address', address),
    row('Job title', data.jobTitle),
    row('Time commitment', data.timeCommitment + (data.timeCommitment === 'Part time with stated hours' && data.hoursPerWeek ? ` (${data.hoursPerWeek} hours per week)` : '')),
    row('Also a director', data.isDirector),
    ...(data.otherVentures === 'Yes' ? [row('Other ventures disclosed', data.venturesText)] : []),
    sep(),
    h2('Pay and equity'),
    row('Remuneration', data.salaryAmount ? `R ${parseFloat(data.salaryAmount).toLocaleString('en-ZA')} per month` : '—'),
    ...(data.salaryDeferral === 'Yes' ? [row('Deferral terms', data.deferralTerms)] : []),
    row('Review mechanism', data.salaryReview),
    row('Shareholding', data.shareholdingRef),
    row('Vesting linked to employment', data.vestingLinked),
    ...(data.vestingLinked === 'Yes' ? [
      row('Good leaver events', data.goodLeaver.join(', ') || '—'),
      row('Bad leaver consequence', data.badLeaverEffect),
    ] : []),
    sep(),
    h2('Intellectual property and exit'),
    row('IP assignment', data.ipAssignment),
    row('Prior IP', data.nothingToDeclare ? 'Nothing to declare' : data.priorIp.map(r => `${r.description} (${r.treatment})`).join('; ') || '—'),
    row('Publicly funded work', data.publiclyFunded),
    row('Restraint of trade', data.restraint),
    ...(data.restraint === 'Yes' ? [
      row('Restraint duration', `${data.restraintMonths} months`),
      row('Restraint area', data.restraintArea),
      row('Restricted activities', data.restraintActivities),
    ] : []),
    row('Resignation ends directorship', data.resignBoth),
    sep(),
    disclaimer(),
  ])
}

// ── Website Terms of Use ──────────────────────────────────────────────────────

export async function buildWebsiteTermsDocx(data: WebsiteTermsData, completedAt: string | null): Promise<Blob> {
  const address = [data.street, data.suburb, data.city, data.province, data.postalCode, data.country].filter(Boolean).join(', ')
  const isIndividual = data.entityType === 'Individual'
  return pack([
    h1('WEBSITE TERMS OF USE'),
    row('Effective date', data.effectiveDate ? new Intl.DateTimeFormat('en-ZA', { day: 'numeric', month: 'long', year: 'numeric' }).format(new Date(`${data.effectiveDate}T00:00:00`)) : fmtDate(completedAt)),
    row('Domains', data.domains.filter(d => d.domain.trim()).map(d => d.domain).join(', ') || '—'),
    sep(),
    h2('Operator'),
    row('Entity type', data.entityType),
    ...(isIndividual
      ? [row('Full names', data.fullNames), row('Identity number', data.idNumber)]
      : [row('Registered name', data.legalName), row('Registration number', data.regNumber), ...(data.tradingName ? [row('Trading name', data.tradingName)] : [])]),
    row('Address', address),
    row('Email', data.email),
    ...(data.phone ? [row('Telephone', data.phone)] : []),
    ...(!isIndividual ? [row('Signatory', `${data.signatoryName} (${data.signatoryCapacity})`)] : []),
    row('Contact email', data.contactEmail),
    row('Site purpose', data.sitePurpose),
    ...(data.sitePurpose === 'Provides a platform between users' ? [row('Platform acknowledgement', data.platformAcknowledged ? 'Recorded — user chose to proceed without Counsel review' : 'Not acknowledged')] : []),
    sep(),
    h2('Features'),
    row('User accounts', data.hasAccounts),
    ...(data.hasAccounts === 'Yes' ? [row('Suspension grounds', data.accountSuspensionGrounds.join(', ') || '—')] : []),
    row('User-generated content', data.hasUgc),
    ...(data.hasUgc === 'Yes' ? [row('UGC licence', data.ugcLicence), row('Moderation and takedown', data.ugcTakedown)] : []),
    row('Payments', data.hasPayments),
    ...(data.hasPayments === 'Yes' && data.refundsRef ? [row('Linked refunds policy', data.refundsRef)] : []),
    row('Third-party links', data.hasThirdPartyLinks),
    sep(),
    h2('Disclaimers and legal'),
    row('Professional advice disclaimer', data.adviceDisclaimer),
    row('Acceptable use restrictions', data.acceptableUse.join('; ') || '—'),
    row('Limitation of liability', data.liabilityCap + (data.liabilityCap === 'A stated amount' && data.liabilityAmount ? ` — R ${parseFloat(data.liabilityAmount).toLocaleString('en-ZA')}` : '')),
    row('Governing law', data.governingLaw),
    row('Jurisdiction', data.jurisdictionCity),
    sep(),
    disclaimer(),
  ])
}

// ── POPIA Records Starter Kit ─────────────────────────────────────────────────

export async function buildPopiaRecordsDocx(d: POPIARecordsData, completedAt: string | null): Promise<Blob> {
  const fmtAddr = (p: POPIARecordsData['breachOwner']) =>
    [p.street, p.building, p.streetName, p.suburb, p.city, p.province, p.postalCode, p.country].filter(Boolean).join(', ')

  const activityRows = d.activities.flatMap((a, i) => [
    h2(`Activity ${i + 1}: ${a.activity || '—'}`),
    row('Purpose', a.purpose),
    row('Categories', a.categories.join(', ') || '—'),
    row('Lawful basis', a.basis),
    row('Recipients', a.recipients),
    row('Retention', a.retention),
    row('Cross-border', a.crossBorder),
    row('Security measures', a.security.join(', ') || '—'),
  ])

  const operatorRows = d.operators.flatMap((o, i) => [
    h2(`Operator ${i + 1}: ${o.name || '—'}`),
    row('Service', o.service),
    row('Country', o.country),
    row('Written agreement', o.hasAgreement),
  ])

  return pack([
    h1('POPIA RECORDS STARTER KIT'),
    row('Responsible party', d.responsibleParty),
    row('Information officer', d.infoOfficer),
    row('Effective date', d.effectiveDate ? new Intl.DateTimeFormat('en-ZA', { day: 'numeric', month: 'long', year: 'numeric' }).format(new Date(`${d.effectiveDate}T00:00:00`)) : fmtDate(completedAt)),
    row('Generated by', 'The Startup Legal'),
    sep(),

    h2('1. Shared Inputs'),
    row('Privacy contact email', d.privacyEmail),
    row('Domains and applications', d.domains),
    row('PI categories', d.piCategories.join(', ') || '—'),
    row('Special PI', d.specialPi.join(', ') || 'None'),
    ...(d.specialPi.length ? [row('Special PI justification', d.specialPiBasis)] : []),
    row('Children\'s data', d.childrenData),
    ...(d.childrenData === 'Yes' ? [row('Children consent mechanism', d.childrenConsent)] : []),
    row('Purposes', d.purposes),
    row('Lawful basis', d.purposesBasis),
    row('Retention', d.retention),
    row('Third parties', d.thirdParties),
    row('Cross-border transfers', d.crossBorder),
    ...(d.crossBorder === 'Yes' ? [row('Countries', d.crossBorderCountries), row('Transfer basis', d.transferBasis)] : []),
    row('Direct marketing', d.directMarketing),
    row('Cookies', d.cookies),
    row('Cookie consent', d.cookieConsent),
    ...(d.analyticsProvider ? [row('Analytics provider', d.analyticsProvider)] : []),
    row('DSR channel', d.dsrChannel),
    row('DSR response days', d.dsrDays),
    row('Security measures', d.securitySummary.join(', ') || '—'),
    sep(),

    h2('2. Processing Register'),
    ...activityRows,
    sep(),

    h2('3. Operators'),
    ...operatorRows,
    ...(d.operators.some(o => o.hasAgreement === 'No') ? [row('Generate missing operator agreements', d.generateOperatorAgreements)] : []),
    sep(),

    h2('4. Incidents and Requests'),
    h2('Breach response owner'),
    row('Full names', d.breachOwner.fullNames),
    row('Identity number', d.breachOwner.idNumber),
    row('Address', fmtAddr(d.breachOwner)),
    row('Email', d.breachOwner.email),
    ...(d.breachOwner.phone ? [row('Telephone', d.breachOwner.phone)] : []),
    h2('Escalation contact'),
    row('Full names', d.breachEscalation.fullNames),
    row('Identity number', d.breachEscalation.idNumber),
    row('Address', fmtAddr(d.breachEscalation)),
    row('Email', d.breachEscalation.email),
    ...(d.breachEscalation.phone ? [row('Telephone', d.breachEscalation.phone)] : []),
    row('Request handling owner', d.dsrOwner),
    row('Security measures in place', d.securityMeasures.join(', ') || '—'),
    row('PAIA manual required', d.paiaManual),
    sep(),

    disclaimer(),
  ])
}

// ── Refunds Policy ────────────────────────────────────────────────────────────

export async function buildRefundsPolicyDocx(data: RefundsPolicyData, completedAt: string | null): Promise<Blob> {
  const isSubscriptions = data.productTypes.includes('Subscriptions')
  return pack([
    h1('REFUNDS AND CANCELLATION POLICY'),
    row('Effective date', data.effectiveDate ? new Intl.DateTimeFormat('en-ZA', { day: 'numeric', month: 'long', year: 'numeric' }).format(new Date(`${data.effectiveDate}T00:00:00`)) : fmtDate(completedAt)),
    row('Business', data.company || '—'),
    row('Contact email', data.refundsEmail || '—'),
    sep(),
    h2('Business and Products'),
    row('What you sell', data.productTypes.join(', ') || '—'),
    row('Sales channel', data.salesChannel || '—'),
    sep(),
    h2('Refund Rules'),
    row('Refunds offered', data.offersRefunds),
    ...(data.offersRefunds === 'No'
      ? [row('Statutory rights', 'Customers retain all statutory rights under applicable consumer protection legislation to return faulty, defective or unsuitable goods.')]
      : [
          row('Refund window', `${data.refundDays} days from delivery or purchase`),
          row('Conditions for a refund', data.refundCondition.join('; ') || '—'),
        ]),
    ...(data.productTypes.includes('Digital downloads') ? [row('Digital download exclusions', data.digitalExclusions.join('; ') || 'None')] : []),
    ...(data.productTypes.includes('Services') ? [row('Services already performed', data.servicesExclusion === 'Yes' ? 'No refund for work already performed (pro rata for unperformed work)' : 'Standard terms')] : []),
    ...(data.productTypes.includes('Physical goods') ? [row('Who pays return shipping', data.returnShipping)] : []),
    ...(isSubscriptions ? [
      sep(),
      h2('Cancellations'),
      row('Cancellation approach', data.cancellationApproach),
      ...(data.cancellationApproach === 'Cancel with notice' && data.cancellationNoticeDays ? [row('Notice period', `${data.cancellationNoticeDays} days`)] : []),
      row('Pro rata refund on cancellation', data.prorataRefund),
    ] : []),
    sep(),
    h2('Refund Process'),
    row('How to request a refund', data.refundProcess),
    row('Information required', data.refundInfoRequired.join('; ') || '—'),
    row('Processing time', `${data.refundProcessingDays} business days`),
    row('Refund method', data.refundMethod),
    sep(),
    disclaimer(),
  ])
}
